// All project data — keyed by slug (matches projects.html cards)
// Each project has a single hero cover image (no other photos available).
const PROJECT_DATA = {
  "01": {
    title: "Packler",
    titleEm: "Packler",
    category: "App mobile",
    year: "2026",
    client: "Packler, plateforme de transport à la demande",
    duration: "10 semaines",
    team: ["Léa Marchand — lead UX", "Tom Bertrand — UI", "Iris Kovac — direction artistique"],
    cover: "uploads/iPhone 1.jpg",
    intro: [
      "Packler, c'est le <em>Uber du déménagement</em>. Tu commandes, un Packler arrive — pour un meuble, un colis, ou tout un appartement.",
      "On a conçu l'app de zéro: parcours instantané, scan IA pour estimer le volume, devis en quelques secondes, suivi en temps réel.",
    ],
    quote: "Le plus dur, c'était de faire tenir un devis de déménagement complet dans le même réflexe qu'une course Uber. On l'a fait.",
    quoteAttr: "Léa Marchand, lead UX",
    results: [
      { n: "3 min", l: "pour obtenir un devis instantané, contre 48h en moyenne ailleurs" },
      { n: "+82%", l: "de conversion sur le parcours de réservation post-refonte" },
      { n: "2", l: "modes connectés — Packler Now (à la demande) et Déménagement (complet)" },
    ],
    deliverables: ["Recherche utilisateur", "Architecture du parcours", "App iOS & Android", "Scan IA volume", "Design system"],
  },
  "02": {
    title: "SG",
    titleEm: "SG",
    category: "Refonte UX",
    year: "2026",
    client: "Société Générale — équipe app mobile",
    duration: "8 semaines",
    team: ["Tom Bertrand — lead", "Camille Roy — UX", "Léa Marchand — UI"],
    cover: "uploads/Holding iPhone 16 Pro Mockup Skin Pack V1 02.jpg",
    intro: [
      "Refonte de la page d'accueil de l'app SG <em>avant connexion</em>: la première chose qu'un client voit en ouvrant son app bancaire.",
      "Objectif: rendre l'écran utile avant même que l'utilisateur tape son code — solde, raccourcis, assistant IA, et accès express aux actions vitales.",
    ],
    quote: "On a transformé un écran de garde en véritable cockpit. Le code, c'est presque devenu une formalité.",
    quoteAttr: "Tom Bertrand, lead",
    results: [
      { n: "-46%", l: "temps moyen pour effectuer un virement depuis l'ouverture de l'app" },
      { n: "+3", l: "actions disponibles sans authentification (consultation, virement, RIB)" },
      { n: "100%", l: "des écrans repassés au crible de l'accessibilité (AAA sur les CTA)" },
    ],
    deliverables: ["Audit UX", "Maquettes avant/après", "Prototype animé", "Spécifications techniques", "Handoff dev"],
  },
  "03": {
    title: "N Dance Center",
    titleEm: "N",
    category: "Site web",
    year: "2025",
    client: "N Dance Center, association de danse — Noisy-le-Grand",
    duration: "14 semaines",
    team: ["Iris Kovac — DA", "Camille Roy — design", "Tom Bertrand — dev"],
    cover: "uploads/iPhone 17 Pro Max Tech Editorial Mockup 2.jpg",
    intro: [
      "Une association de danse (Modern Jazz, Hip-Hop, Dancehall, Afro, Street Dance) qui voulait un vrai site <em>pensé pour leurs besoins</em>: pas un template, pas un Wix.",
      "On a tout développé sur-mesure: inscriptions en ligne, gestion des plannings, espace adhérent, téléchargement du calendrier — adapté à leur fonctionnement réel.",
    ],
    quote: "On voulait un site qui ressemble à la salle: noir, brut, électrique. Pas une plaquette d'association.",
    quoteAttr: "Iris Kovac, direction artistique",
    results: [
      { n: "+ 60%", l: "d'inscriptions à la rentrée suivant le lancement du site" },
      { n: "7", l: "disciplines réparties dans un planning interactif et filtrable" },
      { n: "0", l: "appel téléphonique pour inscrire un adhérent — tout passe en ligne" },
    ],
    deliverables: ["Branding", "Site sur-mesure", "Système d'inscription", "Espace adhérent", "Téléchargement planning PDF"],
  },
  "04": {
    title: "Brûle-jour",
    titleEm: "Brûle-jour",
    category: "E-commerce",
    year: "2025",
    client: "Brûle-jour, maison de bougies artisanales",
    duration: "7 semaines",
    team: ["Camille Roy — DA", "Léa Marchand — design"],
    cover: "uploads/iPhone 17 Pro Max Tech Editorial Mockup 3.jpg",
    intro: [
      "Concept de bougie artisanale française, fabriquée en petits lots. Site <em>e-commerce et éditorial</em> pour porter à la fois l'objet et l'univers.",
      "On a posé un cadre sombre, typographie en serif sculpté, photo en clair-obscur. Le produit respire, le tunnel d'achat suit.",
    ],
    quote: "Une marque qui se vend autant à la lumière d'un écran qu'à celle d'une bougie. C'est tout ce qu'on cherchait.",
    quoteAttr: "Camille Roy, direction artistique",
    results: [
      { n: "x3,4", l: "panier moyen depuis l'ouverture de la boutique" },
      { n: "4,9★", l: "note moyenne sur les 200 premiers avis vérifiés" },
      { n: "30 jours", l: "pour épuiser la première édition limitée" },
    ],
    deliverables: ["Branding & logo", "Direction photo", "Site e-commerce Shopify", "Packaging", "Newsletter"],
  },
  "05": {
    title: "Homy Expert",
    titleEm: "Expert",
    category: "App mobile",
    year: "2025",
    client: "Homy Expert, fintech assurance",
    duration: "12 semaines",
    team: ["Tom Bertrand — lead", "Iris Kovac — design", "Camille Roy — research"],
    cover: "uploads/Phone Mockup_5 qwed.jpg",
    intro: [
      "Homy Expert scanne vos contrats d'assurance et vous dit où vous payez trop. <em>L'app qui fait économiser sans changer de banque</em>.",
      "On a livré une expérience où l'utilisateur dépose un contrat, reçoit une analyse claire, et arbitre. Direction visuelle: sobre, premium, rassurante.",
    ],
    quote: "Le sujet est aride. Le design devait être assez fort pour qu'on ait envie d'ouvrir l'app — même pour parler d'assurance habitation.",
    quoteAttr: "Tom Bertrand, lead",
    results: [
      { n: "468 €", l: "économie moyenne identifiée par utilisateur sur 12 mois" },
      { n: "+71%", l: "rétention semaine 4 après la refonte de l'onboarding" },
      { n: "★ 4,7", l: "note App Store après deux mois en production" },
    ],
    deliverables: ["Recherche utilisateur", "Onboarding", "App iOS & Android", "Identité visuelle", "Site marketing"],
  },
  "06": {
    title: "Sable",
    titleEm: "Sable",
    category: "App mobile",
    year: "2025",
    client: "Sable, concept d'épargne automatique",
    duration: "6 semaines",
    team: ["Iris Kovac — DA", "Léa Marchand — design"],
    cover: "uploads/SC_01.jpg",
    intro: [
      "Concept d'app qui épargne pour vous, <em>en silence</em> — entre vos cafés, vos courses, vos virements.",
      "On a livré une direction art forte: noir profond, or pâle, typo serif italique. L'épargne devient un objet de contemplation, pas une corvée.",
    ],
    quote: "On a refusé toute idée de \"finance ludique\". Sable est lent, calme, presque cérémonieux. C'est ça qui le rend précieux.",
    quoteAttr: "Iris Kovac, direction artistique",
    results: [
      { n: "2 847 €", l: "estimation moyenne d'épargne sur 12 mois sans effort" },
      { n: "01/05", l: "écrans d'onboarding au lieu de 12 — l'essentiel, rien d'autre" },
      { n: "0", l: "notification push — par contrat avec l'utilisateur" },
    ],
    deliverables: ["Concept produit", "Direction artistique", "App iOS", "Onboarding éditorial", "Pitch deck"],
  },
  "07": {
    title: "Denteclair",
    titleEm: "Denteclair",
    category: "Site web",
    year: "2024",
    client: "Denteclair, cabinets dentaires associés (Poissy, Bezons, Vitry)",
    duration: "9 semaines",
    team: ["Léa Marchand — DA", "Tom Bertrand — dev", "Camille Roy — copy"],
    cover: "uploads/pasted-1778787929867-0.png",
    intro: [
      "Trois cabinets dentaires qui voulaient sortir du site \"plaquette PDF en ligne\". Objectif: <em>visibilité locale et prises de rendez-vous en ligne</em>.",
      "On a livré un site éditorialisé, photos chaleureuses, navigation par cabinet, et un système de RDV intégré — SEO local optimisé pour chaque ville.",
    ],
    quote: "Les patients arrivent au cabinet sereins. Ils savent qui ils vont voir, dans quel cabinet, pour quel soin. C'est rare en dentaire.",
    quoteAttr: "Dr. M., associé Denteclair",
    results: [
      { n: "+ 180%", l: "demandes de rendez-vous en ligne sur les 3 premiers mois" },
      { n: "1er", l: "résultat Google sur \"dentiste Poissy\" en 4 mois" },
      { n: "3", l: "cabinets unifiés sous une même marque, mais avec leur identité propre" },
    ],
    deliverables: ["Identité", "Site multi-cabinets", "SEO local", "Système de RDV", "Direction photo"],
  },
  "08": {
    title: "Write or Die",
    titleEm: "Die",
    category: "App mobile",
    year: "2024",
    client: "Write or Die, app de productivité d'écriture",
    duration: "8 semaines",
    team: ["Tom Bertrand — lead", "Iris Kovac — DA"],
    cover: "uploads/pasted-1778787945895-0.png",
    intro: [
      "Une app de productivité qui force à <em>écrire à l'infini</em> — si vous arrêtez, l'écran se brouille. Pas de pause, pas de relecture, pas d'échappatoire.",
      "Direction graphique radicale: rouge incandescent, typographie nerveuse, identité quasi-horrifique. L'app est un dispositif, pas un éditeur de texte.",
    ],
    quote: "Le brief était simple: il faut qu'on ait peur d'arrêter d'écrire. On a livré une app qui te fixe dans le noir.",
    quoteAttr: "Iris Kovac, direction artistique",
    results: [
      { n: "1,2 M", l: "mots écrits cumulés par la communauté en 3 mois" },
      { n: "27 min", l: "durée moyenne d'une session — 5x la moyenne du marché" },
      { n: "viral", l: "couverture éditoriale spontanée (The Verge, Wired, Korii.)" },
    ],
    deliverables: ["Concept produit", "Identité radicale", "App iOS", "Mode \"kamikaze\"", "Site marketing"],
  },
  "09": {
    title: "Anthéa Lounge",
    titleEm: "Lounge",
    category: "Site web",
    year: "2024",
    client: "Anthéa Lounge, salon d'onglerie & esthétique",
    duration: "5 semaines",
    team: ["Camille Roy — DA", "Léa Marchand — design"],
    cover: "uploads/pasted-1778787937302-0.png",
    intro: [
      "Salon d'onglerie haut de gamme qui voulait professionnaliser sa prise de rendez-vous: fini Instagram DM, place à un <em>site de booking</em>.",
      "On a posé une identité féminine, sereine, et un parcours de réservation aussi simple qu'une story — créneaux, prestation, prothésiste, validation.",
    ],
    quote: "Avant, je passais une heure par soir à répondre à des DMs. Maintenant les filles réservent toutes seules, et je dors.",
    quoteAttr: "Anthéa, fondatrice",
    results: [
      { n: "+ 220%", l: "rendez-vous pris en ligne vs. ancien canal Instagram" },
      { n: "12 h", l: "économisées par semaine sur la gestion des réservations" },
      { n: "0", l: "no-show depuis l'activation des rappels SMS automatiques" },
    ],
    deliverables: ["Identité", "Site & booking", "Système de rappels SMS", "Direction photo", "Templates social"],
  },
  "10": {
    title: "Paww",
    titleEm: "Paww",
    category: "App mobile",
    year: "2024",
    client: "Paww, app de bien-être pour animaux de compagnie",
    duration: "11 semaines",
    team: ["Léa Marchand — lead", "Iris Kovac — illustration", "Tom Bertrand — UI"],
    cover: "uploads/1.jpg",
    intro: [
      "Paww comprend le bien-être de vos animaux: sommeil, fréquence cardiaque, comportement, signes d'inconfort. <em>L'amour, ça se suit de près</em>.",
      "On a conçu une app chaleureuse, presque enfantine, avec illustrations sur-mesure — pour que le sujet \"santé animale\" reste tendre et engageant.",
    ],
    quote: "On a fait une app de santé. Mais on a tout fait pour qu'elle ne ressemble pas à une app de santé. C'est ça qui fonctionne.",
    quoteAttr: "Léa Marchand, lead",
    results: [
      { n: "95%", l: "taux de bien-être mesuré chez les animaux suivis depuis 3 mois" },
      { n: "80%", l: "des utilisateurs ouvrent l'app quotidiennement (D1 retention)" },
      { n: "2", l: "espèces couvertes au lancement: chien & chat — plus à venir" },
    ],
    deliverables: ["Recherche utilisateur", "Illustration sur-mesure", "App iOS & Android", "Rapports santé", "Onboarding ludique"],
  },
};

// Provide ordered list of slugs for next/prev
const PROJECT_ORDER = ["01","02","03","04","05","06","07","08","09","10"];

Object.assign(window, { PROJECT_DATA, PROJECT_ORDER });
